server:
  port: 8081
  servlet:
    context-path: /book-service

spring:
  data:
    mongodb:
      authentication-database: admin
      database: book-store
      port: 27017
      host: localhost

keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: getir
  resource: newClient
  public-client: true

